### ISSUE TITLE
readme.md使用攻略参考申请

### ISSUE THREAD

**Issue by tianyilt** [IammyselfYBX/NCEPU_CS_course#4]
您好,很高兴看到更多的同学尝试用github仓库托管课程资料,打破以qq群为单位的信息孤岛,我为自己的学习也做了个[共享库](https://github.com/tianyilt/ecust-CourseShare).

偶然从b站参考gitlab的资料的时候发现您的项目,觉得您的readme的使用攻略比我[目前版本](https://github.com/tianyilt/ecust-CourseShare/blob/master/doc/%E4%B8%8B%E8%BD%BD%E4%B8%80%E4%BB%BD%E6%96%87%E4%BB%B6.md)更加方便,请问是否可以将那些gif也放到我的仓库下,我会写好参考目标的.

同时目前建设过程中发现有很多问题,同学们都在[项目issue](https://github.com/tianyilt/ecust-CourseShare/issues)中进行讨论.如果您有解决的方法,希望能有更进一步的交流,谢谢!

**Comment by IammyselfYBX** [comment]
嗯,可以,如果等你做好了,可以在联系我,到时候我放在我的README里面让更多人收益

**Comment by tianyilt** [comment]
好的谢谢
